### ISSUE TITLE
[Bug Report] Cannot generate python code with simple scaffold.

### ISSUE THREAD

**Issue by jabbera** [Azure/autorest.azure-functions#9]
Troubleshooting:
- Did you try `autorest --reset` and attempt again? Yes/No? Yes

### Setup (please complete the following information): **
- OS: Windows
- OS Version: Windows 10
- Mode: cli
- Language to be generated: python
- Autorest Core version: Please paste the output of `autorest --version` if possible.
```
AutoRest code generation utility [cli version: 3.1.2; node: v12.21.0, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Failure:
Error: Unable to find a valid AutoRest core package '@autorest/core' @ 'true'.
Error: Unable to find a valid AutoRest core package '@autorest/core' @ 'true'.
    at Object.selectVersion (C:\Users\Mike\AppData\Roaming\npm\node_modules\autorest\dist\src_autorest-as-a-service_ts-src_coloring_ts.js:303:23)
```
### Describe the bug

Trying to generate a function scaffold via:
```
autorest --input-file=test.yaml --python  --azure-functions-python --no-namespace-folders:true --debug --version:3.0.6320 --output-folder:./generated-azfunctions 
```

Yields the error: 
Process() cancelled due to exception : Cannot resolve pipeline stage 'openapi-document/identity'. / Error: Cannot resolve pipeline stage 'openapi-document/identity'.

test.yaml:
```
openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /list:
    get:
      description: Returns a list of stuff
      responses:
        '200':
          description: Successful response
```

#### To Reproduce
```
autorest --input-file=test.yaml --python  --azure-functions-python --no-namespace-folders:true --debug --version:3.0.6320 --output-folder:./generated-azfunctions 

AutoRest code generation utility [cli version: 3.1.2; node: v12.21.0, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from C:\Users\Mike\.autorest\@autorest_core@3.0.6320
   Loading AutoRest core      'C:\Users\Mike\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist' (3.0.6320)
   Loading AutoRest extension '@microsoft.azure/autorest.python' (~3.0.56->3.0.62)
   Loading AutoRest extension '@autorest/azure-functions-python' (latest->0.1.0-preview)
   Loading AutoRest extension '@autorest/modelerfour' (4.15.414->4.15.414)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.44->2.3.44)
Process() cancelled due to exception : Cannot resolve pipeline stage 'openapi-document/identity'. / Error: Cannot resolve pipeline stage 'openapi-document/identity'.
```

Trying to generate

**Sample File attached** 

test.yaml
```
openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /list:
    get:
      description: Returns a list of stuff
      responses:
        '200':
          description: Successful response
```
**Stacktrace**

<details>
<summary>Click to expand the full stacktrace</summary>
Process() cancelled due to exception : Cannot resolve pipeline stage 'openapi-document/identity'. / Error: Cannot resolve pipeline stage 'openapi-document/identity'.
    at resolvePipelineStageName (C:\Users\Mike\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js:62:15)
    at C:\Users\Mike\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js:82:108
    at Array.map (<anonymous>)
    at createNodesAndSuffixes (C:\Users\Mike\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js:82:97)
    at buildPipeline (C:\Users\Mike\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js:132:9)
    at Object.runPipeline (C:\Users\Mike\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js:228:22)
    at async processInternal (C:\Users\Mike\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\autorest-core.js:120:17)
    at async currentMain (C:\Users\Mike\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\app.js:335:24)
    at async mainImpl (C:\Users\Mike\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\app.js:510:20)
    at async main (C:\Users\Mike\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\app.js:537:20)
  Error: Cannot resolve pipeline stage 'openapi-document/identity'.
[3.67 s] Shutting Down.
</details>

**Additional context**

**Comment by vrdmr** [comment]
Hi @jabbera - Looks like some npm autorest core issue on your box. Could you please try upgrading the autorest on your box?
```
npm install -g autorest@latest
npm install -g @autorest/core@latest
```

I made a small change to your yaml - adding the `operationId` to the list call, and tried generating the function. It worked. Attaching the debug logs at the end. Also removed `--python` as that generates the Python SDK (Azure SDK) and we don't want to generate it.
```yaml
➜ cat x.yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /list:
    get:
      operationId: getlist
      description: Returns a list of stuff
      responses:
        '200':
          description: Successful response
```

Autorest's commandline output
```bash
autorest \
    --input-file=x.yaml \
    --azure-functions-python \
    --no-namespace-folders:true \
    --debug --version:3.0.6320 \
    --output-folder:./generated-azfunctions
```

autorest version's output
```bash
➜ autorest --version
AutoRest code generation utility [cli version: 3.1.2; node: v12.17.0, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Failure:
Error: Unable to find a valid AutoRest core package '@autorest/core' @ 'true'.
Error: Unable to find a valid AutoRest core package '@autorest/core' @ 'true'.
    at Object.selectVersion (/Users/varadmeru/.nvm/versions/node/v12.17.0/lib/node_modules/autorest/dist/src_autorest-as-a-service_ts-src_coloring_ts.js:303:23)
```

Output of the commandline
```bash
~/tmp
➜ tree generated-azfunctions
generated-azfunctions
├── README.md
├── getlist
│   ├── __init__.py
│   └── function.json
├── host.json
├── local.settings.json
├── proxies.json
└── requirements.txt

1 directory, 7 files
```

`__init__.py`:
![image](https://user-images.githubusercontent.com/1047040/110639936-23f6f800-8165-11eb-8878-ddc6e2d1307a.png)

`function.json`:
```json
➜ cat generated-azfunctions/getlist/function.json
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "get"
      ],
      "route": "list"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ],
  "disabled": false
}
```


<details>
<summary>Click to expand the full debug output</summary>

```
AutoRest code generation utility [cli version: 3.1.2; node: v12.17.0, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from /Users/varadmeru/.autorest/@autorest_core@3.0.6320
   Loading AutoRest core      '/Users/varadmeru/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist' (3.0.6320)
   Loading AutoRest extension '@autorest/azure-functions-python' (latest->0.1.0-preview)
   Loading AutoRest extension '@autorest/modelerfour' (4.15.414->4.15.414)
Executing: /Users/varadmeru/.autorest/@autorest_azure-functions-python@0.1.0-preview/node_modules/@autorest/azure-functions-python/venv/bin/python3 -m autorest.jsonrpc.server
DEBUG [2.17 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [2.17 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [2.17 s]: pipeline-emitter - START inputs = 0
DEBUG [2.21 s]: configuration-emitter - START inputs = 0
DEBUG [2.21 s]: pipeline-emitter - END [0.04 s]
DEBUG [2.21 s]: configuration-emitter - END [0.04 s]
DEBUG [2.21 s]: swagger-document/loader-swagger - END [0.04 s]
DEBUG [2.21 s]: swagger-document/individual/transform - SKIPPING
DEBUG [2.21 s]: swagger-document/individual/schema-validator-swagger - SKIPPING
DEBUG [2.22 s]: swagger-document/identity - SKIPPING
DEBUG [2.22 s]: swagger-document/individual/identity - SKIPPING
DEBUG [2.22 s]: openapi-document/openapi-document-converter - SKIPPING
DEBUG [2.22 s]: openapi-document/loader-openapi - END [0.05 s]
DEBUG [2.22 s]: openapi-document/individual/transform - START inputs = 1
DEBUG [2.22 s]: openapi-document/individual/transform - END [0 s]
DEBUG [2.22 s]: openapi-document/individual/schema-validator-openapi - START inputs = 1
DEBUG [2.23 s]: openapi-document/individual/schema-validator-openapi - END [0 s]
DEBUG [2.23 s]: openapi-document/individual/identity - START inputs = 1
DEBUG [2.23 s]: openapi-document/individual/identity - END [0 s]
DEBUG [2.25 s]: openapi-document/transform - START inputs = 1
DEBUG [2.25 s]: openapi-document/transform - END [0 s]
DEBUG [2.25 s]: openapi-document/allof-cleaner - START inputs = 1
DEBUG [2.25 s]: openapi-document/allof-cleaner - END [0 s]
DEBUG [2.25 s]: openapi-document/tree-shaker - START inputs = 1
DEBUG [2.25 s]: openapi-document/tree-shaker - END [0 s]
DEBUG [2.25 s]: openapi-document/multi-api-merger - START inputs = 1
DEBUG [2.25 s]: openapi-document/multi-api-merger - END [0 s]
DEBUG [2.25 s]: openapi-document/components-cleaner - START inputs = 1
DEBUG [2.26 s]: openapi-document/components-cleaner - END [0 s]
DEBUG [2.26 s]: openapi-document/component-modifiers - START inputs = 1
DEBUG [2.26 s]: openapi-document/component-modifiers - END [0 s]
DEBUG [2.26 s]: openapi-document/api-version-parameter-handler - START inputs = 1
DEBUG [2.26 s]: openapi-document/api-version-parameter-handler - END [0 s]
DEBUG [2.26 s]: openapi-document/profile-filter - START inputs = 1
DEBUG [2.26 s]: openapi-document/profile-filter - END [0 s]
DEBUG [2.26 s]: openapi-document/model-deduplicator - START inputs = 1
DEBUG [2.26 s]: openapi-document/emitter - START inputs = 1
DEBUG [2.26 s]: openapi-document/model-deduplicator - END [0 s]
DEBUG [2.26 s]: openapi-document/enum-deduplicator - START inputs = 1
DEBUG [2.26 s]: openapi-document/emitter - END [0 s]
DEBUG [2.26 s]: openapi-document/enum-deduplicator - END [0 s]
DEBUG [2.26 s]: openapi-document/subset-reducer - START inputs = 1
DEBUG [2.26 s]: openapi-document/subset-reducer - END [0 s]
DEBUG [2.33 s]: openapi-document/quick-check - START inputs = 1
DEBUG [2.33 s]: openapi-document/multi-api/reset-identity - START inputs = 1
DEBUG [2.33 s]: openapi-document/quick-check - END [0 s]
DEBUG [2.33 s]: openapi-document/multi-api/reset-identity - END [0 s]
DEBUG [2.33 s]: openapi-document/multi-api/identity - START inputs = 1
DEBUG [2.33 s]: openapi-document/multi-api/identity - END [0 s]
DEBUG [2.33 s]: openapi-document/multi-api/emitter - START inputs = 1
DEBUG [2.33 s]: python - START inputs = 1
DEBUG [2.33 s]: prechecker - START inputs = 1
DEBUG [2.33 s]: python - END [0 s]
DEBUG [2.33 s]: openapi-document/multi-api/emitter - END [0 s]

WARNING (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
DEBUG [2.34 s]: prechecker - END [0.01 s]
DEBUG [2.34 s]: modelerfour - START inputs = 3
DEBUG [2.36 s]: modelerfour - END [0.01 s]
DEBUG [2.36 s]: modelerfour/new-transform - START inputs = 2
DEBUG [2.36 s]: modelerfour/new-transform - END [0 s]
DEBUG [2.36 s]: modelerfour/flattener - START inputs = 2
DEBUG [2.37 s]: modelerfour/flattener - END [0 s]
DEBUG [2.37 s]: modelerfour/flattener/new-transform - START inputs = 2
DEBUG [2.37 s]: modelerfour/flattener/new-transform - END [0 s]
DEBUG [2.37 s]: modelerfour/grouper - START inputs = 2
DEBUG [2.38 s]: modelerfour/grouper - END [0 s]
DEBUG [2.38 s]: modelerfour/grouper/new-transform - START inputs = 2
DEBUG [2.38 s]: modelerfour/grouper/new-transform - END [0 s]
DEBUG [2.38 s]: modelerfour/pre-namer - START inputs = 2
DEBUG [2.39 s]: modelerfour/pre-namer - END [0.01 s]
DEBUG [2.39 s]: modelerfour/pre-namer/new-transform - START inputs = 2
DEBUG [2.41 s]: modelerfour/pre-namer/new-transform - END [0.01 s]
DEBUG [2.41 s]: modelerfour/checker - START inputs = 4
DEBUG [2.42 s]: modelerfour/checker - END [0 s]
DEBUG [2.42 s]: modelerfour/identity - START inputs = 2
DEBUG [2.42 s]: modelerfour/identity - END [0 s]
DEBUG [2.42 s]: python/m2r - START inputs = 2
DEBUG [2.42 s]: modelerfour/emitter - START inputs = 2
DEBUG [2.42 s]: modelerfour/notags/emitter - START inputs = 2
DEBUG [2.42 s]: modelerfour/emitter - END [0 s]
DEBUG [2.42 s]: modelerfour/notags/emitter - END [0 s]
DEBUG [2.42 s]: [main.Process:32] Autorest called process with plugin_name 'm2r' and session_id: 'session_7'
DEBUG [3.35 s]: [main.Process:46] Starting plugin M2R
DEBUG [3.35 s]: [autorest.jsonrpc.stdstream.list_inputs:81] Calling list inputs to Autorest
DEBUG [3.35 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 86'
DEBUG [3.35 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.35 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 86 bytes message
DEBUG [3.35 s]: [autorest.process:47] Possible Inputs: ['code-model-v4.yaml', 'code-model-v4-no-tags.yaml']
DEBUG [3.35 s]: [autorest.jsonrpc.stdstream.read_file:74] Asking content for file code-model-v4-no-tags.yaml
DEBUG [3.35 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 1710'
DEBUG [3.35 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.35 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 1710 bytes message
DEBUG [3.37 s]: [autorest.jsonrpc.stdstream.write_file:64] Writing a file: code-model-v4-no-tags.yaml
DEBUG [3.37 s]: python/m2r - END [0.94 s]
DEBUG [3.37 s]: python/namer - START inputs = 1
DEBUG [3.37 s]: [main.Process:32] Autorest called process with plugin_name 'namer' and session_id: 'session_8'
DEBUG [3.39 s]: [main.Process:46] Starting plugin Namer
DEBUG [3.39 s]: [autorest.jsonrpc.stdstream.list_inputs:81] Calling list inputs to Autorest
DEBUG [3.39 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 65'
DEBUG [3.39 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.39 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 65 bytes message
DEBUG [3.39 s]: [autorest.process:47] Possible Inputs: ['code-model-v4-no-tags.yaml']
DEBUG [3.39 s]: [autorest.jsonrpc.stdstream.read_file:74] Asking content for file code-model-v4-no-tags.yaml
DEBUG [3.39 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 1492'
DEBUG [3.39 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.39 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 1492 bytes message
DEBUG [3.4 s]: [autorest.jsonrpc.stdstream.write_file:64] Writing a file: code-model-v4-no-tags.yaml
DEBUG [3.4 s]: python/namer - END [0.03 s]
DEBUG [3.4 s]: python/codegen - START inputs = 1
DEBUG [3.4 s]: [main.Process:32] Autorest called process with plugin_name 'codegen' and session_id: 'session_9'
DEBUG [3.95 s]: [main.Process:46] Starting plugin CodeGenerator
DEBUG [3.95 s]: [autorest.jsonrpc.stdstream.list_inputs:81] Calling list inputs to Autorest
DEBUG [3.95 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 65'
DEBUG [3.95 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.95 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 65 bytes message
DEBUG [3.95 s]: [autorest.codegen.process:230] Possible Inputs: ['code-model-v4-no-tags.yaml']
DEBUG [3.95 s]: [autorest.jsonrpc.stdstream.read_file:74] Asking content for file code-model-v4-no-tags.yaml
DEBUG [3.95 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 2089'
DEBUG [3.95 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.95 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 2089 bytes message
DEBUG [3.96 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: azure-arm
DEBUG [3.96 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 40'
DEBUG [3.96 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.96 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 40 bytes message
DEBUG [3.96 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: add-credentials
DEBUG [3.96 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: add-credential
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: credential-scopes
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: credential-scopes
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: header-text
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 220'
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 220 bytes message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: head-as-boolean
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: keep-version-file
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: no-async
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: no-namespace-folders
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: basic-setup-py
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: package-name
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.97 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [4.02 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [4.02 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: package-version
DEBUG [4.02 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [4.02 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [4.02 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [4.02 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: client-side-validation
DEBUG [4.02 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [4.02 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [4.02 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [4.02 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: trace
DEBUG [4.02 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [4.02 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [4.02 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [4.03 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: multiapi
DEBUG [4.03 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [4.03 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [4.03 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [4.03 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: generate-metadata
DEBUG [4.03 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [4.03 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [4.03 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [4.03 s]: [autorest.codegen.models.operation_group.from_yaml:81] Parsing model operation group
DEBUG [4.03 s]: [autorest.codegen.models.operation.from_yaml:286] Parsing getlist operation
DEBUG [4.03 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: namespace
DEBUG [4.03 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [4.03 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [4.03 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [4.03 s]: [autorest.codegen._create_code_model:103] Namespace parameter was None
DEBUG [4.03 s]: [autorest.codegen.models.code_model._populate_schema:281] Looking for id 140491873487488 for member <Parameter>
DEBUG [4.03 s]: [autorest.codegen.serializers.serialize:37] AzureFunctionsPythonSerializer serializing now
DEBUG [4.04 s]: [autorest.codegen.serializers.azure_functions.python.serialize:56] Generating Functions
DEBUG [4.06 s]: [autorest.jsonrpc.stdstream.write_file:64] Writing a file: getlist/init.py
DEBUG [4.1 s]: [autorest.jsonrpc.stdstream.write_file:64] Writing a file: getlist/function.json
DEBUG [4.1 s]: [autorest.codegen.serializers.azure_functions.python.serialize:63] Generating Function App contents
DEBUG [4.11 s]: [autorest.jsonrpc.stdstream.write_file:64] Writing a file: host.json
DEBUG [4.11 s]: [autorest.jsonrpc.stdstream.write_file:64] Writing a file: requirements.txt
DEBUG [4.11 s]: [autorest.jsonrpc.stdstream.write_file:64] Writing a file: local.settings.json
DEBUG [4.13 s]: [autorest.jsonrpc.stdstream.write_file:64] Writing a file: .gitignore
DEBUG [4.14 s]: [autorest.jsonrpc.stdstream.write_file:64] Writing a file: .funcignore
DEBUG [4.14 s]: [autorest.jsonrpc.stdstream.write_file:64] Writing a file: proxies.json
DEBUG [4.15 s]: [autorest.jsonrpc.stdstream.write_file:64] Writing a file: README.md
DEBUG [4.15 s]: [autorest.jsonrpc.stdstream.write_file:64] Writing a file: .vscode/extensions.json
DEBUG [4.15 s]: [autorest.codegen.serializers.azure_functions.python.serialize:69] Generating python model folders
DEBUG [4.15 s]: python/codegen - END [0.74 s]
DEBUG [4.15 s]: python/codegen/emitter - START inputs = 10
DEBUG [4.15 s]: Emitting 'python-files' at file:///Users/varadmeru/tmp/generated-azfunctions/getlist/init.py
DEBUG [4.15 s]: Emitting 'python-files' at file:///Users/varadmeru/tmp/generated-azfunctions/getlist/function.json
DEBUG [4.15 s]: Emitting 'python-files' at file:///Users/varadmeru/tmp/generated-azfunctions/host.json
DEBUG [4.15 s]: Emitting 'python-files' at file:///Users/varadmeru/tmp/generated-azfunctions/requirements.txt
DEBUG [4.15 s]: Emitting 'python-files' at file:///Users/varadmeru/tmp/generated-azfunctions/local.settings.json
DEBUG [4.15 s]: Emitting 'python-files' at file:///Users/varadmeru/tmp/generated-azfunctions/.gitignore
DEBUG [4.16 s]: Emitting 'python-files' at file:///Users/varadmeru/tmp/generated-azfunctions/.funcignore
DEBUG [4.16 s]: Emitting 'python-files' at file:///Users/varadmeru/tmp/generated-azfunctions/proxies.json
DEBUG [4.16 s]: Emitting 'python-files' at file:///Users/varadmeru/tmp/generated-azfunctions/README.md
DEBUG [4.16 s]: Emitting 'python-files' at file:///Users/varadmeru/tmp/generated-azfunctions/.vscode/extensions.json
DEBUG [4.16 s]: python/codegen/emitter - END [0 s]
[4.16 s] Clearing Folders.
[4.16 s] Writing Outputs.
[4.16 s] Generation Complete
[4.16 s] Shutting Down.
[4.16 s] Exiting.
```

</details>

**Comment by jabbera** [comment]
Many thanks! I'm good now!
